trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'

- script: |
    cd server
    npm install

- task: AzureWebApp@1
  inputs:
    azureSubscription: '6a6a871f-f14e-43d4-9136-5638e7419075'
    appName: 'usercrud-api-hksarkar'
    package: 'server'